// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpbw4W3YI9HqUlNBdeFhHnqMscYBRTyTQ',
    appId: '1:297790351022:web:ef8602eded3478717aef3f',
    messagingSenderId: '297790351022',
    projectId: 'prueba-02-52806',
    authDomain: 'prueba-02-52806.firebaseapp.com',
    storageBucket: 'prueba-02-52806.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBtIkvhxDsjZ1G3Ol_xooNrsePNCDggxE',
    appId: '1:297790351022:android:b2883ed41986dc8b7aef3f',
    messagingSenderId: '297790351022',
    projectId: 'prueba-02-52806',
    storageBucket: 'prueba-02-52806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Mxljm7h4YXX2kPWtRz6AHduF8kMX9Ew',
    appId: '1:297790351022:ios:20d57e6223c94c1f7aef3f',
    messagingSenderId: '297790351022',
    projectId: 'prueba-02-52806',
    storageBucket: 'prueba-02-52806.appspot.com',
    iosBundleId: 'com.example.prueba02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Mxljm7h4YXX2kPWtRz6AHduF8kMX9Ew',
    appId: '1:297790351022:ios:20d57e6223c94c1f7aef3f',
    messagingSenderId: '297790351022',
    projectId: 'prueba-02-52806',
    storageBucket: 'prueba-02-52806.appspot.com',
    iosBundleId: 'com.example.prueba02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpbw4W3YI9HqUlNBdeFhHnqMscYBRTyTQ',
    appId: '1:297790351022:web:a29a17735caf3c5e7aef3f',
    messagingSenderId: '297790351022',
    projectId: 'prueba-02-52806',
    authDomain: 'prueba-02-52806.firebaseapp.com',
    storageBucket: 'prueba-02-52806.appspot.com',
  );
}
